import { test } from 'node:test';
import assert from 'node:assert/strict';
import { planCartSheet } from '../api/cart-sheet-plan.js';
const header=['Téléphone','Statut','Nom','Ville','Adresse','Offre','Total (DH)','Premier enregistrement (UTC)','Campagne','Source','Annonce','Dernière saisie (UTC)','_Capture auto'];
const jh=['phone','started_ms','updated_ms','status','name','city','address','offer','total','campaign','source','ad'];
const t=1791500000000;
const entry=(phone='0611111111',at=t,name='First')=>[phone,t-10000,at,'Abandonné',name,'','', '1kg',299,'campaign','fb','ad'];
function apply(snapshot,plan){const rows=structuredClone(snapshot);for(const request of JSON.parse(plan.body).requests){if(!request.updateCells)continue;const u=request.updateCells;while(rows.length<=u.start.rowIndex)rows.push([]);u.rows[0].values.forEach((c,i)=>{const v=c.userEnteredValue;rows[u.start.rowIndex][u.start.columnIndex+i]=v.stringValue??v.numberValue;});}return rows;}
test('new leads append, literal phone and details contain no formulas',()=>{const p=planCartSheet({sheetId:1,snapshot:[header],journal:[jh,entry(),entry('0622222222',t+1000)]});const rows=apply([header],p);assert.equal(rows[1][0],'0611111111');assert.equal(rows[2][0],'0622222222');assert.equal(p.added,2);assert.ok(!p.body.includes('formulaValue'));assert.ok(p.body.includes('appeler.html#0611111111'));});
test('later captures refresh auto fields but preserve operator corrections, including status',()=>{let rows=apply([header],planCartSheet({sheetId:1,snapshot:[header],journal:[jh,entry()]}));rows[1][3]='Casablanca';rows[1][4]='Manual address';rows[1][1]='Confirmé';const p=planCartSheet({sheetId:1,snapshot:rows,journal:[jh,entry(),[...entry('0611111111',t+5000,'Full name')].map((v,i)=>i===5?'Rabat':i===6?'Auto address':v)]});rows=apply(rows,p);assert.equal(rows[1][2],'Full name');assert.equal(rows[1][3],'Casablanca');assert.equal(rows[1][4],'Manual address');assert.equal(rows[1][1],'Confirmé');assert.equal(p.added,0);});
test('manual name changes and clearing fields survive later snapshots',()=>{let rows=apply([header],planCartSheet({sheetId:1,snapshot:[header],journal:[jh,entry()]}));rows[1][2]='Corrected';rows=apply(rows,planCartSheet({sheetId:1,snapshot:rows,journal:[jh,entry('0611111111',t+2000,'Auto changed')]}));assert.equal(rows[1][2],'Corrected');rows[1][2]='';rows=apply(rows,planCartSheet({sheetId:1,snapshot:rows,journal:[jh,entry('0611111111',t+4000,'Auto again')]}));assert.equal(rows[1][2],'');});
test('completion updates default status and preserves manual status',()=>{let rows=apply([header],planCartSheet({sheetId:1,snapshot:[header],journal:[jh,entry(),entry('0622222222')]}));rows[2][1]='Annulé';rows=apply(rows,planCartSheet({sheetId:1,snapshot:rows,journal:[jh,entry(),entry('0622222222'),['0611111111',0,t+10000,'Envoyé'],['0622222222',0,t+10000,'Envoyé']]}));assert.equal(rows[1][1],'Envoyé');assert.equal(rows[2][1],'Annulé');});
test('corrected phone keeps immutable capture key and link follows corrected phone',()=>{let rows=apply([header],planCartSheet({sheetId:1,snapshot:[header],journal:[jh,entry()]}));rows[1][0]='0633333333';const p=planCartSheet({sheetId:1,snapshot:rows,journal:[jh,entry('0611111111',t+2000)]});assert.equal(p.added,0);assert.ok(p.body.includes('appeler.html#0633333333'));});
test('out of order events use newest snapshot and do not move existing rows',()=>{let rows=apply([header],planCartSheet({sheetId:1,snapshot:[header],journal:[jh,entry(),entry('0622222222')]}));const p=planCartSheet({sheetId:1,snapshot:rows,journal:[jh,entry('0611111111',t+8000,'Newest'),entry('0611111111',t+4000,'Older'),entry('0622222222')]});rows=apply(rows,p);assert.equal(rows[1][2],'Newest');assert.equal(rows[2][0],'0622222222');});
