const html = String.raw`<!doctype html>
<html lang="ar" dir="rtl">
<head>
  <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <title>AzarBio | فواكه مجففة بالتبريد للعائلة</title>
  <meta name="description" content="خليط فواكه مجففة بالتبريد، مقرمش وجاهز للأكل. عروض عائلية مع التوصيل بالمجان اليوم.">
  <meta property="og:title" content="AzarBio | عرض العائلة"><meta property="og:description" content="التوصيل بالمجان اليوم فقط">
  <meta property="og:image" content="/consumer-real-product.webp"><meta name="theme-color" content="#0c5a38">
  <link rel="preload" as="image" href="/consumer-real-product.webp" fetchpriority="high">
  <style>
    :root{--g:#0b5837;--g2:#173f2c;--cream:#fff9ed;--gold:#f1b93a;--red:#bb2d2d;--ink:#17221b;--muted:#637067}
    *{box-sizing:border-box}html{scroll-behavior:smooth;overflow-x:hidden;max-width:100%}body{margin:0;width:100%;max-width:100%;overflow-x:hidden;background:#fffdf8;color:var(--ink);font-family:Tahoma,Arial,sans-serif;line-height:1.55}.wrap{width:min(1080px,calc(100% - 28px));max-width:100%;margin:auto}
    .top{background:linear-gradient(90deg,#9f211f,#ce3a31);color:#fff;text-align:center;padding:10px 8px;font-weight:900;font-size:16px;position:sticky;top:0;z-index:20}.timer{font-variant-numeric:tabular-nums;color:#ffe680;margin-inline-start:7px}
    header{padding:16px 0 8px}.brand{font-size:26px;font-weight:1000;color:var(--g)}.brand small{display:block;font-size:12px;color:var(--muted);font-weight:700}
    .hero{display:grid;grid-template-columns:1.03fr .97fr;gap:28px;align-items:center;padding:12px 0 30px}.hero-media{position:relative}.hero img{width:100%;aspect-ratio:1/1;object-fit:cover;border-radius:28px;box-shadow:0 18px 46px #173f2c2b}.real{position:absolute;right:14px;bottom:14px;background:#fff;border-radius:99px;padding:8px 12px;font-size:12px;font-weight:900;box-shadow:0 6px 20px #0002}
    .eyebrow{color:var(--red);font-weight:900}.hero h1{font-size:clamp(32px,5vw,58px);line-height:1.12;margin:7px 0 12px;color:var(--g2)}.hero p{font-size:19px;margin:0 0 16px}.checks{display:grid;gap:8px;margin:14px 0}.checks span:before{content:'✓';display:inline-grid;place-items:center;width:22px;height:22px;background:#daf5e5;color:var(--g);border-radius:50%;margin-left:7px;font-weight:900}
    .cta{display:inline-flex;align-items:center;justify-content:center;min-height:54px;padding:0 24px;border:0;border-radius:14px;background:var(--g);color:#fff;text-decoration:none;font-size:18px;font-weight:900;box-shadow:0 9px 0 #073a25;cursor:pointer}.cta:active{transform:translateY(3px);box-shadow:0 6px 0 #073a25}
    section{padding:44px 0}.soft{background:#f4f8f2}.title{text-align:center;font-size:clamp(27px,4vw,42px);line-height:1.2;margin:0 0 9px;color:var(--g2)}.sub{text-align:center;color:var(--muted);margin:0 auto 24px;max-width:680px}
    .offers{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.offer{background:#fff;border:2px solid #dbe8df;border-radius:20px;padding:20px;position:relative;cursor:pointer;transition:.15s}.offer:hover,.offer.selected{border-color:var(--g);transform:translateY(-3px);box-shadow:0 12px 30px #0b583719}.offer.best{border-color:var(--gold)}.badge{position:absolute;top:-13px;right:16px;background:var(--gold);border-radius:99px;padding:4px 11px;font-size:12px;font-weight:1000}.qty{font-size:24px;font-weight:1000;color:var(--g)}.price{font-size:37px;font-weight:1000;margin:7px 0}.price small{font-size:16px}.free{color:#167244;font-weight:900}.old{color:#8b948e;text-decoration:line-through;font-size:14px}
    .proof{display:grid;grid-template-columns:1fr 1fr;gap:22px;align-items:center}.proof img{width:100%;border-radius:22px;max-height:560px;object-fit:cover}.cards{display:grid;gap:12px}.card{background:#fff;border:1px solid #e3e9e4;border-radius:16px;padding:16px;box-shadow:0 8px 24px #173f2c10}.card b{color:var(--g)}.reviews{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px}.review{min-width:0;background:#fff;border:1px solid #dce7df;border-radius:18px;padding:18px;box-shadow:0 9px 26px #173f2c12}.stars{color:#f1b322;font-size:22px;letter-spacing:2px;direction:ltr;text-align:right}.review p{font-size:16px;margin:8px 0 14px}.review small{color:var(--muted);font-weight:800}.trustline{text-align:center;color:var(--g);font-weight:900;margin-top:18px}
    .order{display:grid;grid-template-columns:.85fr 1.15fr;gap:24px;align-items:start}.summary{background:var(--g2);color:#fff;border-radius:24px;padding:24px;position:sticky;top:64px}.summary strong{font-size:30px}.summary ul{padding-right:20px}.form{min-width:0;background:#fff;border:1px solid #dce6df;border-radius:24px;padding:24px;box-shadow:0 16px 50px #173f2c18}.field{margin-bottom:14px}.field label{display:block;font-weight:900;margin-bottom:6px}.field input{width:100%;height:54px;border:2px solid #cedbd2;border-radius:12px;padding:0 14px;font-size:18px;outline:none}.field input:focus{border-color:var(--g);box-shadow:0 0 0 4px #0b583714}.choice{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-bottom:16px}.choice button{width:100%;min-width:0;min-height:82px;border:3px solid #d6e0d8;background:#fff;border-radius:15px;padding:10px 6px;font:1000 19px/1.35 Tahoma,Arial,sans-serif;color:var(--g2);cursor:pointer}.choice-price{display:block;font-size:21px}.choice button.on{background:#e8f6ec;border-color:var(--g);color:var(--g);box-shadow:inset 0 0 0 1px var(--g)}.submit{width:100%;min-height:58px;font-size:20px}.micro{text-align:center;color:var(--muted);font-size:13px;margin-top:12px}.error{display:none;background:#fff0f0;color:#9c2020;border-radius:10px;padding:10px;margin-bottom:10px}
    .wa{position:fixed;left:18px;bottom:88px;width:58px;height:58px;border-radius:50%;display:grid;place-items:center;background:#25d366;color:#fff;text-decoration:none;font-size:30px;box-shadow:0 8px 24px #0003;z-index:30}.sticky{display:none}.modal{position:fixed;inset:0;background:#0009;z-index:50;display:none;place-items:center;padding:18px}.modal.show{display:grid}.modal-box{background:#fff;border-radius:24px;padding:28px;width:min(500px,100%);text-align:center}.modal .ok{font-size:54px}.modal h2{color:var(--g);font-size:28px;margin:4px}.modal p{font-size:18px}
    footer{padding:34px;text-align:center;color:var(--muted)}
    @media(max-width:760px){.wrap{width:calc(100% - 20px);max-width:620px}.hero{grid-template-columns:minmax(0,1fr);padding-top:4px}.hero-copy,.hero-media{min-width:0}.hero-copy{order:-1}.hero h1{font-size:37px}.hero p{font-size:17px}.offers,.proof,.order,.reviews{grid-template-columns:minmax(0,1fr)}.offer{padding:17px}.proof img{max-height:460px}.summary{position:static}.choice{grid-template-columns:minmax(0,1fr)}.choice button{min-height:92px;font-size:22px}.choice-price{font-size:24px}.form{padding:18px 14px}.top{font-size:14px}.sticky{display:block;position:fixed;left:0;right:0;bottom:0;width:100%;background:#fff;padding:10px 14px calc(10px + env(safe-area-inset-bottom));z-index:25;box-shadow:0 -5px 20px #0002}.sticky .cta{width:100%;min-height:52px}.wa{left:14px;bottom:84px}body{padding-bottom:72px}}
  </style>
</head>
<body>
  <div class="top">🚚 التوصيل بالمجان إلى نهاية اليوم <span class="timer" id="timer">--:--:--</span></div>
  <header class="wrap"><div class="brand">AzarBio<small>فواكه مجففة بالتبريد</small></div></header>
  <main>
    <div class="wrap hero">
      <div class="hero-media"><img src="/consumer-real-product.webp" width="900" height="900" alt="صورة حقيقية لخليط فواكه AzarBio داخل الكيس" fetchpriority="high"><span class="real">📱 صورة حقيقية للمنتوج بعدسة الهاتف</span></div>
      <div class="hero-copy"><div class="eyebrow">عرض العائلة • التوصيل مجاني اليوم</div><h1>مذاق الفواكه المقرمش… في كل وقت</h1><p>خليط متنوع من الفواكه المجففة بالتبريد، جاهز للأكل ومعبأ بعناية للحفاظ على القرمشة والمذاق.</p><div class="checks"><span>مانجا، فراولة، كيوي، موز، تفاح وجاك فروت</span><span>بدون قلي — خفيف ومقرمش</span><span>الدفع عند الاستلام بعد تأكيد الطلب</span></div><a class="cta" href="#order">اختار العرض واطلب الآن</a></div>
    </div>
    <section class="soft" id="offers"><div class="wrap"><h2 class="title">اختار الكمية المناسبة ليك</h2><p class="sub">الثمن واضح والتوصيل بالمجان اليوم. نعيطو ليك لتأكيد المعلومات قبل الإرسال.</p><div class="offers">
      <article class="offer" data-offer="500G"><div class="qty">500 غرام</div><div class="price">199 <small>درهم</small></div><div class="free">✓ التوصيل بالمجان</div></article>
      <article class="offer" data-offer="1KG"><div class="qty">1 كيلو</div><div class="price">299 <small>درهم</small></div><div class="free">✓ التوصيل بالمجان</div></article>
      <article class="offer best selected" data-offer="2KG_PLUS_500G"><span class="badge">الأكثر توفيراً</span><div class="qty">2 كيلو + 500غ هدية</div><div class="price">499 <small>درهم</small></div><div class="old">بدل شراء 2.5 كيلو بثمن منفصل</div><div class="free">✓ 500غ والتوصيل بالمجان</div></article>
    </div></div></section>
    <section><div class="wrap"><h2 class="title">آراء حقيقية من زبنائنا</h2><p class="sub">مقتطفات مختصرة من رسائل التوصل بالطلبات، بدون نشر الأسماء حفاظاً على الخصوصية.</p><div class="reviews">
      <article class="review"><div class="stars">★ رأي موثّق</div><p>“السلعة نقية وكاتشهي، والجودة طوب ديال طوب.”</p><small>رسالة بعد التوصل</small></article>
      <article class="review"><div class="stars">★ رأي موثّق</div><p>“وصلني الكوموند في الوقت، الاحترافية والجودة مضمونة.”</p><small>رسالة بعد التوصل</small></article>
      <article class="review"><div class="stars">★ رأي موثّق</div><p>“التوصيل سريع والسلعة نقية بزاف.”</p><small>رسالة بعد التوصل</small></article>
      <article class="review"><div class="stars">★ رأي موثّق</div><p>“الساشيات جاو ناضيين، الله يسر.”</p><small>رسالة بعد التوصل</small></article>
      <article class="review"><div class="stars">★ رأي موثّق</div><p>“السلعة نقية، ماشي بحال كاين فالسوق.”</p><small>رسالة بعد التوصل</small></article>
      <article class="review"><div class="stars">★ رأي موثّق</div><p>“تبارك الله عليكم، السلعة نقية.”</p><small>رسالة بعد التوصل</small></article>
    </div><div class="trustline">★ الثقة &nbsp; ★ الجودة &nbsp; ★ التوصيل إلى جميع المدن</div></div></section>
    <section><div class="wrap proof"><img src="/consumer-real-product.webp" width="900" height="900" loading="lazy" alt="شكل الفواكه الحقيقي داخل كيس AzarBio"><div><h2 class="title" style="text-align:right">كتشوف بالضبط شنو غيوصلك</h2><p>صورة حقيقية للمنتوج بلا مؤثرات: قطع فواكه متنوعة داخل كيس محكم، سهلة للتقديم فالدار أو الخدمة.</p><div class="cards"><div class="card"><b>“السلعة نقية والجودة طوب”</b><br>رأي زبون بعد التوصل بالطلب.</div><div class="card"><b>“التوصيل سريع والسلعة نقية بزاف”</b><br>من تجربة زبون مع AzarBio.</div><div class="card"><b>توصيل إلى جميع المدن</b><br>التأكيد بالهاتف والدفع عند الاستلام.</div></div></div></div></section>
    <section class="soft" id="order"><div class="wrap order"><aside class="summary"><div>العرض المختار</div><strong id="sumName">2 كيلو + 500غ مجاناً</strong><p><span id="sumPrice">499</span> درهم</p><ul><li>التوصيل: مجاني اليوم</li><li>الدفع عند الاستلام</li><li>سنتصل بك لتأكيد الطلب</li></ul></aside><form class="form" id="form"><h2 class="title" style="text-align:right;font-size:30px">سجّل طلبك في أقل من دقيقة</h2><div class="choice"><button type="button" data-choice="500G">500 غرام<span class="choice-price">199 درهم</span></button><button type="button" data-choice="1KG">1 كيلو<span class="choice-price">299 درهم</span></button><button type="button" class="on" data-choice="2KG_PLUS_500G">2 كيلو + 500غ مجاناً<span class="choice-price">499 درهم</span></button></div><input type="hidden" name="offer_package" value="2KG_PLUS_500G"><input name="website" tabindex="-1" autocomplete="off" style="position:absolute;left:-9999px" aria-hidden="true"><div class="field"><label for="name">الاسم الكامل</label><input id="name" name="name" autocomplete="name" required minlength="2" placeholder="مثال: محمد العلوي"></div><div class="field"><label for="phone">رقم الهاتف</label><input id="phone" name="phone" inputmode="tel" autocomplete="tel" required placeholder="06 أو 07..."></div><div class="field"><label for="city">المدينة</label><input id="city" name="city" autocomplete="address-level2" required placeholder="مثال: الدار البيضاء"></div><div class="field"><label for="address">العنوان <small style="font-weight:normal;color:#6b756e">(اختياري — يمكن إعطاؤه في الهاتف)</small></label><input id="address" name="address" autocomplete="street-address" placeholder="الحي أو العنوان"></div><div class="error" id="error"></div><button class="cta submit" type="submit" id="submit">أكد طلبي — التوصيل بالمجان</button><div class="micro">🔒 معلوماتك تستعمل فقط لتأكيد وإرسال الطلب. لا أداء مسبق.</div></form></div></section>
  </main>
  <footer>AzarBio © <span id="year"></span> — خدمة الزبناء عبر واتساب</footer>
  <a class="wa" href="https://wa.me/212708101099?text=%D8%B3%D9%84%D8%A7%D9%85%D8%8C%20%D8%A8%D8%BA%D9%8A%D8%AA%20%D9%86%D8%B9%D8%B1%D9%81%20%D8%A3%D9%83%D8%AB%D8%B1%20%D8%B9%D9%84%D9%89%20%D8%B9%D8%B1%D8%B6%20%D8%A7%D9%84%D8%B9%D8%A7%D8%A6%D9%84%D8%A9" target="_blank" rel="noopener" aria-label="تواصل معنا عبر واتساب">◔</a>
  <div class="sticky"><a class="cta" href="#order">اطلب الآن — التوصيل بالمجان</a></div>
  <div class="modal" id="thanks" role="dialog" aria-modal="true"><div class="modal-box"><div class="ok">✅</div><h2>هنيئاً لك!</h2><p>لقد استفدت من التوصيل بالمجان. نتصل بك قريباً للتحقق من المعلومات وإرسال طلبك في أقرب وقت.</p><b id="thanksOffer"></b></div></div>
  <script>
  (function(){
    var offers={'500G':{name:'500 غرام',price:199},'1KG':{name:'1 كيلو',price:299},'2KG_PLUS_500G':{name:'2 كيلو + 500غ مجاناً',price:499}};
    var started=Date.now(), selected='2KG_PLUS_500G', form=document.getElementById('form');
    function choose(key){selected=key;form.offer_package.value=key;document.getElementById('sumName').textContent=offers[key].name;document.getElementById('sumPrice').textContent=offers[key].price;document.querySelectorAll('[data-choice]').forEach(function(b){b.classList.toggle('on',b.dataset.choice===key)});document.querySelectorAll('[data-offer]').forEach(function(b){b.classList.toggle('selected',b.dataset.offer===key)})}
    document.querySelectorAll('[data-choice]').forEach(function(b){b.onclick=function(){choose(b.dataset.choice)}});document.querySelectorAll('[data-offer]').forEach(function(b){b.onclick=function(){choose(b.dataset.offer);document.getElementById('order').scrollIntoView()}});
    function tick(){var now=new Date(), parts=new Intl.DateTimeFormat('en-GB',{timeZone:'Africa/Casablanca',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).formatToParts(now), h=+parts.find(x=>x.type==='hour').value%24,m=+parts.find(x=>x.type==='minute').value,s=+parts.find(x=>x.type==='second').value,left=86400-(h*3600+m*60+s),hh=String(Math.floor(left/3600)).padStart(2,'0'),mm=String(Math.floor(left%3600/60)).padStart(2,'0'),ss=String(left%60).padStart(2,'0');document.getElementById('timer').textContent=hh+':'+mm+':'+ss}tick();setInterval(tick,1000);document.getElementById('year').textContent=new Date().getFullYear();
    form.onsubmit=async function(e){e.preventDefault();var btn=document.getElementById('submit'),err=document.getElementById('error');err.style.display='none';btn.disabled=true;btn.textContent='جاري تسجيل الطلب...';var fd=new FormData(form),q=new URLSearchParams(location.search),data=Object.fromEntries(fd.entries());data.client_elapsed_ms=Date.now()-started;data.landing_page=location.href;['utm_source','utm_medium','utm_campaign','utm_content','utm_term'].forEach(k=>data[k]=q.get(k)||'');try{var r=await fetch('/api/consumer-lead',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}),j=await r.json();if(!r.ok)throw new Error(j.error||'error');document.getElementById('thanksOffer').textContent=offers[selected].name+' — '+offers[selected].price+' درهم';document.getElementById('thanks').classList.add('show');if(window.fbq)fbq('track','Lead',{content_name:'AzarBio B2C '+offers[selected].name,value:offers[selected].price,currency:'MAD'});if(window.gtag)gtag('event','generate_lead',{currency:'MAD',value:offers[selected].price,offer:selected,page_type:'B2C'});}catch(x){var msg=x.message==='duplicate_phone'?'سبق تسجّل طلب بهذا الرقم. غادي نتواصلو معاك قريباً.':'تعذر تسجيل الطلب الآن. حاول مرة أخرى أو تواصل معنا عبر واتساب.';err.textContent=msg;err.style.display='block';btn.disabled=false;btn.textContent='أكد طلبي — التوصيل بالمجان'}};
  })();
  </script>
</body></html>`;

export default function handler(req, res) {
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.setHeader('Cache-Control', 'public, max-age=0, s-maxage=300, stale-while-revalidate=86400');
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.end(html);
}
